python wahoo-map-creator-osmosis.py American-Oceania	
python wahoo-map-creator-osmosis.py Australia	
python wahoo-map-creator-osmosis.py Cook-Islands	
python wahoo-map-creator-osmosis.py Fiji	
python wahoo-map-creator-osmosis.py Ile-de-Clipperton	
python wahoo-map-creator-osmosis.py Kiribati	
python wahoo-map-creator-osmosis.py Marshall-Islands	
python wahoo-map-creator-osmosis.py Micronesia	
python wahoo-map-creator-osmosis.py Nauru	
python wahoo-map-creator-osmosis.py New-Caledonia	
python wahoo-map-creator-osmosis.py New-Zealand	
python wahoo-map-creator-osmosis.py Niue	
python wahoo-map-creator-osmosis.py Palau	
python wahoo-map-creator-osmosis.py Papua-New-Guinea	
python wahoo-map-creator-osmosis.py Pitcairn-Islands	
python wahoo-map-creator-osmosis.py polynesie-francaise	
python wahoo-map-creator-osmosis.py Samoa	
python wahoo-map-creator-osmosis.py Solomon-Islands	
python wahoo-map-creator-osmosis.py Tokelau	
python wahoo-map-creator-osmosis.py Tonga	
python wahoo-map-creator-osmosis.py Tuvalu	
python wahoo-map-creator-osmosis.py Vanuatu	
python wahoo-map-creator-osmosis.py Wallis-et-Futuna
python wahoo-map-creator-osmosis.py australia-oceania