python wahoo-map-creator-osmosis-route.py Afghanistan	
python wahoo-map-creator-osmosis-route.py Armenia	
python wahoo-map-creator-osmosis-route.py Azerbaijan	
python wahoo-map-creator-osmosis-route.py Bangladesh	
python wahoo-map-creator-osmosis-route.py Bhutan	
python wahoo-map-creator-osmosis-route.py Cambodia	
python wahoo-map-creator-osmosis-route.py China	
python wahoo-map-creator-osmosis-route.py East-Timor
python wahoo-map-creator-osmosis-route.py GCC-States	
python wahoo-map-creator-osmosis-route.py Central-Zone
python wahoo-map-creator-osmosis-route.py Eastern-Zone
python wahoo-map-creator-osmosis-route.py North-Eastern-Zone
python wahoo-map-creator-osmosis-route.py Northern-Zone
python wahoo-map-creator-osmosis-route.py Southern-Zone
python wahoo-map-creator-osmosis-route.py Western-Zone
python wahoo-map-creator-osmosis-route.py India	
python wahoo-map-creator-osmosis-route.py Java
python wahoo-map-creator-osmosis-route.py Kalimantan
python wahoo-map-creator-osmosis-route.py Maluku
python wahoo-map-creator-osmosis-route.py Nusa-Tenggara
python wahoo-map-creator-osmosis-route.py Papua
python wahoo-map-creator-osmosis-route.py Sulawesi
python wahoo-map-creator-osmosis-route.py Sumatra
python wahoo-map-creator-osmosis-route.py Indonesia	
python wahoo-map-creator-osmosis-route.py Iran	
python wahoo-map-creator-osmosis-route.py Iraq	
python wahoo-map-creator-osmosis-route.py Israel-and-Palestine	
python wahoo-map-creator-osmosis-route.py Chubu	
python wahoo-map-creator-osmosis-route.py Chugoku	
python wahoo-map-creator-osmosis-route.py Hokkaido	
python wahoo-map-creator-osmosis-route.py Kansai	
python wahoo-map-creator-osmosis-route.py Kanto	
python wahoo-map-creator-osmosis-route.py Kyushu	
python wahoo-map-creator-osmosis-route.py Shikoku	
python wahoo-map-creator-osmosis-route.py Tohoku	
python wahoo-map-creator-osmosis-route.py Japan	
python wahoo-map-creator-osmosis-route.py Jordan	
python wahoo-map-creator-osmosis-route.py Kazakhstan	
python wahoo-map-creator-osmosis-route.py Kyrgyzstan	
python wahoo-map-creator-osmosis-route.py Laos	
python wahoo-map-creator-osmosis-route.py Lebanon	
python wahoo-map-creator-osmosis-route.py Malaysia-Singapore-Brunei	
python wahoo-map-creator-osmosis-route.py Maldives	
python wahoo-map-creator-osmosis-route.py Mongolia	
python wahoo-map-creator-osmosis-route.py Myanmar	
python wahoo-map-creator-osmosis-route.py Nepal	
python wahoo-map-creator-osmosis-route.py North-Korea	
python wahoo-map-creator-osmosis-route.py Pakistan	
python wahoo-map-creator-osmosis-route.py Philippines	
python wahoo-map-creator-osmosis-route.py South-Korea	
python wahoo-map-creator-osmosis-route.py Sri-Lanka	
python wahoo-map-creator-osmosis-route.py Syria	
python wahoo-map-creator-osmosis-route.py Taiwan	
python wahoo-map-creator-osmosis-route.py Tajikistan	
python wahoo-map-creator-osmosis-route.py Thailand	
python wahoo-map-creator-osmosis-route.py Turkmenistan	
python wahoo-map-creator-osmosis-route.py Uzbekistan	
python wahoo-map-creator-osmosis-route.py Vietnam	
python wahoo-map-creator-osmosis-route.py Yemen	
python wahoo-map-creator-osmosis-route.py Asia