python wahoo-map-creator-osmosis.py Algeria	
python wahoo-map-creator-osmosis.py Angola	
python wahoo-map-creator-osmosis.py Benin	
python wahoo-map-creator-osmosis.py Botswana	
python wahoo-map-creator-osmosis.py Burkina-Faso	
python wahoo-map-creator-osmosis.py Burundi	
python wahoo-map-creator-osmosis.py Cameroon	
python wahoo-map-creator-osmosis.py Canary-Islands	
python wahoo-map-creator-osmosis.py Cape-Verde	
python wahoo-map-creator-osmosis.py Central-African-Republic	
python wahoo-map-creator-osmosis.py Chad	
python wahoo-map-creator-osmosis.py Comores	
python wahoo-map-creator-osmosis.py Congo-Brazzaville	
python wahoo-map-creator-osmosis.py Congo-Democratic-Republic	
python wahoo-map-creator-osmosis.py Djibouti	
python wahoo-map-creator-osmosis.py Egypt	
python wahoo-map-creator-osmosis.py Equatorial-Guinea	
python wahoo-map-creator-osmosis.py Eritrea	
python wahoo-map-creator-osmosis.py Ethiopia	
python wahoo-map-creator-osmosis.py Gabon	
python wahoo-map-creator-osmosis.py Ghana	
python wahoo-map-creator-osmosis.py Guinea	
python wahoo-map-creator-osmosis.py Guinea-Bissau	
python wahoo-map-creator-osmosis.py Ivory-Coast	
python wahoo-map-creator-osmosis.py Kenya	
python wahoo-map-creator-osmosis.py Lesotho	
python wahoo-map-creator-osmosis.py Liberia	
python wahoo-map-creator-osmosis.py Libya	
python wahoo-map-creator-osmosis.py Madagascar	
python wahoo-map-creator-osmosis.py Malawi	
python wahoo-map-creator-osmosis.py Mali	
python wahoo-map-creator-osmosis.py Mauritania	
python wahoo-map-creator-osmosis.py Mauritius	
python wahoo-map-creator-osmosis.py Morocco	
python wahoo-map-creator-osmosis.py Mozambique	
python wahoo-map-creator-osmosis.py Namibia	
python wahoo-map-creator-osmosis.py Niger	
python wahoo-map-creator-osmosis.py Nigeria	
python wahoo-map-creator-osmosis.py Rwanda	
python wahoo-map-creator-osmosis.py Saint-Helena-Ascension-and-Tristan-da-Cunha	
python wahoo-map-creator-osmosis.py Sao-Tome-and-Principe	
python wahoo-map-creator-osmosis.py Senegal-and-Gambia	
python wahoo-map-creator-osmosis.py Seychelles	
python wahoo-map-creator-osmosis.py Sierra-Leone	
python wahoo-map-creator-osmosis.py Somalia	
python wahoo-map-creator-osmosis.py South-Africa	
python wahoo-map-creator-osmosis.py South-Sudan	
python wahoo-map-creator-osmosis.py Sudan	
python wahoo-map-creator-osmosis.py Swaziland	
python wahoo-map-creator-osmosis.py Tanzania	
python wahoo-map-creator-osmosis.py Togo	
python wahoo-map-creator-osmosis.py Tunisia	
python wahoo-map-creator-osmosis.py Uganda	
python wahoo-map-creator-osmosis.py Zambia	
python wahoo-map-creator-osmosis.py Zimbabwe	
python wahoo-map-creator-osmosis.py Africa
