python wahoo-map-creator-osmosis-route.py central-fed-district
python wahoo-map-creator-osmosis-route.py crimean-fed-district
python wahoo-map-creator-osmosis-route.py far-eastern-fed-district
python wahoo-map-creator-osmosis-route.py kaliningrad
python wahoo-map-creator-osmosis-route.py north-caucasus-fed-district
python wahoo-map-creator-osmosis-route.py northwestern-fed-district
python wahoo-map-creator-osmosis-route.py siberian-fed-district
python wahoo-map-creator-osmosis-route.py south-fed-district
python wahoo-map-creator-osmosis-route.py ural-fed-district
python wahoo-map-creator-osmosis-route.py volga-fed-district
