python wahoo-map-creator-osmosis.py Argentina	
python wahoo-map-creator-osmosis.py Bolivia	
python wahoo-map-creator-osmosis.py centro-oeste
python wahoo-map-creator-osmosis.py nordeste
python wahoo-map-creator-osmosis.py norte
python wahoo-map-creator-osmosis.py sudeste
python wahoo-map-creator-osmosis.py sul
python wahoo-map-creator-osmosis.py Brazil	
python wahoo-map-creator-osmosis.py Chile	
python wahoo-map-creator-osmosis.py Colombia	
python wahoo-map-creator-osmosis.py Ecuador	
python wahoo-map-creator-osmosis.py Guyana
python wahoo-map-creator-osmosis.py Paraguay	
python wahoo-map-creator-osmosis.py Peru	
python wahoo-map-creator-osmosis.py Suriname	
python wahoo-map-creator-osmosis.py Uruguay	
python wahoo-map-creator-osmosis.py Venezuela	
python wahoo-map-creator-osmosis.py south-america