python wmc-e.py bahamas
python wmc-e.py belize
python wmc-e.py central-america
python wmc-e.py costa-rica
python wmc-e.py cuba
python wmc-e.py el-salvador
python wmc-e.py guatemala
python wmc-e.py haiti-and-domrep
python wmc-e.py honduras
python wmc-e.py jamaica
python wmc-e.py nicaragua
python wmc-e.py panama