python wahoo-map-creator-osmosis.py Afghanistan	
python wahoo-map-creator-osmosis.py Armenia	
python wahoo-map-creator-osmosis.py Azerbaijan	
python wahoo-map-creator-osmosis.py Bangladesh	
python wahoo-map-creator-osmosis.py Bhutan	
python wahoo-map-creator-osmosis.py Cambodia	
python wahoo-map-creator-osmosis.py China	
python wahoo-map-creator-osmosis.py East-Timor
python wahoo-map-creator-osmosis.py GCC-States	
python wahoo-map-creator-osmosis.py Central-Zone
python wahoo-map-creator-osmosis.py Eastern-Zone
python wahoo-map-creator-osmosis.py North-Eastern-Zone
python wahoo-map-creator-osmosis.py Northern-Zone
python wahoo-map-creator-osmosis.py Southern-Zone
python wahoo-map-creator-osmosis.py Western-Zone
python wahoo-map-creator-osmosis.py India	
python wahoo-map-creator-osmosis.py Java
python wahoo-map-creator-osmosis.py Kalimantan
python wahoo-map-creator-osmosis.py Maluku
python wahoo-map-creator-osmosis.py Nusa-Tenggara
python wahoo-map-creator-osmosis.py Papua
python wahoo-map-creator-osmosis.py Sulawesi
python wahoo-map-creator-osmosis.py Sumatra
python wahoo-map-creator-osmosis.py Indonesia	
python wahoo-map-creator-osmosis.py Iran	
python wahoo-map-creator-osmosis.py Iraq	
python wahoo-map-creator-osmosis.py Israel-and-Palestine	
python wahoo-map-creator-osmosis.py Chubu	
python wahoo-map-creator-osmosis.py Chugoku	
python wahoo-map-creator-osmosis.py Hokkaido	
python wahoo-map-creator-osmosis.py Kansai	
python wahoo-map-creator-osmosis.py Kanto	
python wahoo-map-creator-osmosis.py Kyushu	
python wahoo-map-creator-osmosis.py Shikoku	
python wahoo-map-creator-osmosis.py Tohoku	
python wahoo-map-creator-osmosis.py Japan	
python wahoo-map-creator-osmosis.py Jordan	
python wahoo-map-creator-osmosis.py Kazakhstan	
python wahoo-map-creator-osmosis.py Kyrgyzstan	
python wahoo-map-creator-osmosis.py Laos	
python wahoo-map-creator-osmosis.py Lebanon	
python wahoo-map-creator-osmosis.py Malaysia-Singapore-Brunei	
python wahoo-map-creator-osmosis.py Maldives	
python wahoo-map-creator-osmosis.py Mongolia	
python wahoo-map-creator-osmosis.py Myanmar	
python wahoo-map-creator-osmosis.py Nepal	
python wahoo-map-creator-osmosis.py North-Korea	
python wahoo-map-creator-osmosis.py Pakistan	
python wahoo-map-creator-osmosis.py Philippines	
python wahoo-map-creator-osmosis.py South-Korea	
python wahoo-map-creator-osmosis.py Sri-Lanka	
python wahoo-map-creator-osmosis.py Syria	
python wahoo-map-creator-osmosis.py Taiwan	
python wahoo-map-creator-osmosis.py Tajikistan	
python wahoo-map-creator-osmosis.py Thailand	
python wahoo-map-creator-osmosis.py Turkmenistan	
python wahoo-map-creator-osmosis.py Uzbekistan	
python wahoo-map-creator-osmosis.py Vietnam	
python wahoo-map-creator-osmosis.py Yemen	
python wahoo-map-creator-osmosis.py Asia