python wahoo-map-creator-osmosis.py argentina
python wahoo-map-creator-osmosis.py bolivia
python wahoo-map-creator-osmosis.py brazil
python wahoo-map-creator-osmosis.py centro-oeste
python wahoo-map-creator-osmosis.py chile
python wahoo-map-creator-osmosis.py colombia
python wahoo-map-creator-osmosis.py ecuador
python wahoo-map-creator-osmosis.py guyana
python wahoo-map-creator-osmosis.py nordeste
python wahoo-map-creator-osmosis.py norte
python wahoo-map-creator-osmosis.py paraguay
python wahoo-map-creator-osmosis.py peru
python wahoo-map-creator-osmosis.py sudeste
python wahoo-map-creator-osmosis.py sul
python wahoo-map-creator-osmosis.py suriname
python wahoo-map-creator-osmosis.py uruguay
python wahoo-map-creator-osmosis.py venezuela
