python wahoo-map-creator-osmosis-route.py Argentina	
python wahoo-map-creator-osmosis-route.py Bolivia	
python wahoo-map-creator-osmosis-route.py centro-oeste
python wahoo-map-creator-osmosis-route.py nordeste
python wahoo-map-creator-osmosis-route.py norte
python wahoo-map-creator-osmosis-route.py sudeste
python wahoo-map-creator-osmosis-route.py sul
python wahoo-map-creator-osmosis-route.py Brazil	
python wahoo-map-creator-osmosis-route.py Chile	
python wahoo-map-creator-osmosis-route.py Colombia	
python wahoo-map-creator-osmosis-route.py Ecuador	
python wahoo-map-creator-osmosis-route.py Guyana
python wahoo-map-creator-osmosis-route.py Paraguay	
python wahoo-map-creator-osmosis-route.py Peru	
python wahoo-map-creator-osmosis-route.py Suriname	
python wahoo-map-creator-osmosis-route.py Uruguay	
python wahoo-map-creator-osmosis-route.py Venezuela	
python wahoo-map-creator-osmosis-route.py south-america