python wmc-e.py central-fed-district
python wmc-e.py crimean-fed-district
python wmc-e.py far-eastern-fed-district
python wmc-e.py kaliningrad
python wmc-e.py north-caucasus-fed-district
python wmc-e.py northwestern-fed-district
python wmc-e.py siberian-fed-district
python wmc-e.py south-fed-district
python wmc-e.py ural-fed-district
python wmc-e.py volga-fed-district
