python wahoo-map-creator-osmosis-route.py American-Oceania	
python wahoo-map-creator-osmosis-route.py Australia	
python wahoo-map-creator-osmosis-route.py Cook-Islands	
python wahoo-map-creator-osmosis-route.py Fiji	
python wahoo-map-creator-osmosis-route.py Ile-de-Clipperton	
python wahoo-map-creator-osmosis-route.py Kiribati	
python wahoo-map-creator-osmosis-route.py Marshall-Islands	
python wahoo-map-creator-osmosis-route.py Micronesia	
python wahoo-map-creator-osmosis-route.py Nauru	
python wahoo-map-creator-osmosis-route.py New-Caledonia	
python wahoo-map-creator-osmosis-route.py New-Zealand	
python wahoo-map-creator-osmosis-route.py Niue	
python wahoo-map-creator-osmosis-route.py Palau	
python wahoo-map-creator-osmosis-route.py Papua-New-Guinea	
python wahoo-map-creator-osmosis-route.py Pitcairn-Islands	
python wahoo-map-creator-osmosis-route.py polynesie-francaise	
python wahoo-map-creator-osmosis-route.py Samoa	
python wahoo-map-creator-osmosis-route.py Solomon-Islands	
python wahoo-map-creator-osmosis-route.py Tokelau	
python wahoo-map-creator-osmosis-route.py Tonga	
python wahoo-map-creator-osmosis-route.py Tuvalu	
python wahoo-map-creator-osmosis-route.py Vanuatu	
python wahoo-map-creator-osmosis-route.py Wallis-et-Futuna
python wahoo-map-creator-osmosis-route.py australia-oceania