python wmc-e.py anhui
python wmc-e.py beijing
python wmc-e.py chongqing
python wmc-e.py fujian
python wmc-e.py gansu
python wmc-e.py guangdong
python wmc-e.py guangxi
python wmc-e.py guizhou
python wmc-e.py hainan
python wmc-e.py hebei
python wmc-e.py heilongjiang
python wmc-e.py henan
python wmc-e.py hong-kong
python wmc-e.py hubei
python wmc-e.py hunan
python wmc-e.py inner-mongolia
python wmc-e.py jiangsu
python wmc-e.py jiangxi
python wmc-e.py jilin
python wmc-e.py liaoning
python wmc-e.py macau
python wmc-e.py ningxia
python wmc-e.py qinghai
python wmc-e.py shaanxi
python wmc-e.py shandong
python wmc-e.py shanghai
python wmc-e.py shanxi
python wmc-e.py sichuan
python wmc-e.py tianjin
python wmc-e.py tibet
python wmc-e.py xinjiang
python wmc-e.py yunnan
python wmc-e.py zhejiang
