python wmc-e.py afghanistan
python wmc-e.py anhui
python wmc-e.py armenia
python wmc-e.py azerbaijan
python wmc-e.py bangladesh
python wmc-e.py beijing
python wmc-e.py bhutan
python wmc-e.py cambodia
python wmc-e.py central-zone
python wmc-e.py chongqing
python wmc-e.py chubu
python wmc-e.py chugoku
python wmc-e.py east-timor
python wmc-e.py eastern-zone
python wmc-e.py fujian
python wmc-e.py gansu
python wmc-e.py gcc-states
python wmc-e.py guangdong
python wmc-e.py guangxi
python wmc-e.py guizhou
python wmc-e.py hainan
python wmc-e.py hebei
python wmc-e.py heilongjiang
python wmc-e.py henan
python wmc-e.py hokkaido
python wmc-e.py hong-kong
python wmc-e.py hubei
python wmc-e.py hunan
python wmc-e.py indonesia
python wmc-e.py inner-mongolia
python wmc-e.py iran
python wmc-e.py iraq
python wmc-e.py israel-and-palestine
python wmc-e.py japan
python wmc-e.py java
python wmc-e.py jiangsu
python wmc-e.py jiangxi
python wmc-e.py jilin
python wmc-e.py jordan
python wmc-e.py kalimantan
python wmc-e.py kansai
python wmc-e.py kanto
python wmc-e.py kazakhstan
python wmc-e.py kyrgyzstan
python wmc-e.py kyushu
python wmc-e.py laos
python wmc-e.py lebanon
python wmc-e.py liaoning
python wmc-e.py macau
python wmc-e.py malaysia-singapore-brunei
python wmc-e.py maldives
python wmc-e.py maluku
python wmc-e.py mongolia
python wmc-e.py myanmar
python wmc-e.py nepal
python wmc-e.py ningxia
python wmc-e.py north-eastern-zone
python wmc-e.py north-korea
python wmc-e.py northern-zone
python wmc-e.py nusa-tenggara
python wmc-e.py pakistan
python wmc-e.py papua
python wmc-e.py philippines
python wmc-e.py qinghai
python wmc-e.py shaanxi
python wmc-e.py shandong
python wmc-e.py shanghai
python wmc-e.py shanxi
python wmc-e.py shikoku
python wmc-e.py sichuan
python wmc-e.py south-korea
python wmc-e.py southern-zone
python wmc-e.py sri-lanka
python wmc-e.py sulawesi
python wmc-e.py sumatra
python wmc-e.py syria
python wmc-e.py taiwan
python wmc-e.py tajikistan
python wmc-e.py thailand
python wmc-e.py tianjin
python wmc-e.py tibet
python wmc-e.py tohoku
python wmc-e.py turkmenistan
python wmc-e.py uzbekistan
python wmc-e.py vietnam
python wmc-e.py western-zone
python wmc-e.py xinjiang
python wmc-e.py yemen
python wmc-e.py yunnan
python wmc-e.py zhejiang
