python wahoo-map-creator-osmosis-route.py Alberta	
python wahoo-map-creator-osmosis-route.py British-Columbia	
python wahoo-map-creator-osmosis-route.py Manitoba	
python wahoo-map-creator-osmosis-route.py New-Brunswick	
python wahoo-map-creator-osmosis-route.py Newfoundland-and-Labrador	
python wahoo-map-creator-osmosis-route.py Northwest-Territories	
python wahoo-map-creator-osmosis-route.py Nova-Scotia	
python wahoo-map-creator-osmosis-route.py Nunavut	
python wahoo-map-creator-osmosis-route.py Ontario	
python wahoo-map-creator-osmosis-route.py Prince-Edward-Island	
python wahoo-map-creator-osmosis-route.py Quebec	
python wahoo-map-creator-osmosis-route.py Saskatchewan	
python wahoo-map-creator-osmosis-route.py Yukon	
python wahoo-map-creator-osmosis-route.py Canada
python wahoo-map-creator-osmosis-route.py Greenland
python wahoo-map-creator-osmosis-route.py Mexico
python wahoo-map-creator-osmosis-route.py us/Alabama	
python wahoo-map-creator-osmosis-route.py us/Alaska	
python wahoo-map-creator-osmosis-route.py us/Arizona	
python wahoo-map-creator-osmosis-route.py us/Arkansas	
python wahoo-map-creator-osmosis-route.py us/California	
python wahoo-map-creator-osmosis-route.py us/Colorado	
python wahoo-map-creator-osmosis-route.py us/Connecticut	
python wahoo-map-creator-osmosis-route.py us/Delaware	
python wahoo-map-creator-osmosis-route.py us/District-of-Columbia	
python wahoo-map-creator-osmosis-route.py us/Florida	
python wahoo-map-creator-osmosis-route.py us/Georgia	
python wahoo-map-creator-osmosis-route.py us/Hawaii	
python wahoo-map-creator-osmosis-route.py us/Idaho	
python wahoo-map-creator-osmosis-route.py us/Illinois	
python wahoo-map-creator-osmosis-route.py us/Indiana	
python wahoo-map-creator-osmosis-route.py us/Iowa	
python wahoo-map-creator-osmosis-route.py us/Kansas	
python wahoo-map-creator-osmosis-route.py us/Kentucky	
python wahoo-map-creator-osmosis-route.py us/Louisiana	
python wahoo-map-creator-osmosis-route.py us/Maine	
python wahoo-map-creator-osmosis-route.py us/Maryland	
python wahoo-map-creator-osmosis-route.py us/Massachusetts	
python wahoo-map-creator-osmosis-route.py us/Michigan	
python wahoo-map-creator-osmosis-route.py us/Minnesota	
python wahoo-map-creator-osmosis-route.py us/Mississippi	
python wahoo-map-creator-osmosis-route.py us/Missouri	
python wahoo-map-creator-osmosis-route.py us/Montana	
python wahoo-map-creator-osmosis-route.py us/Nebraska	
python wahoo-map-creator-osmosis-route.py us/Nevada	
python wahoo-map-creator-osmosis-route.py us/New-Hampshire	
python wahoo-map-creator-osmosis-route.py us/New-Jersey	
python wahoo-map-creator-osmosis-route.py us/New-Mexico	
python wahoo-map-creator-osmosis-route.py us/New-York	
python wahoo-map-creator-osmosis-route.py us/North-Carolina	
python wahoo-map-creator-osmosis-route.py us/North-Dakota	
python wahoo-map-creator-osmosis-route.py us/Ohio	
python wahoo-map-creator-osmosis-route.py us/Oklahoma	
python wahoo-map-creator-osmosis-route.py us/Oregon	
python wahoo-map-creator-osmosis-route.py us/Pennsylvania	
python wahoo-map-creator-osmosis-route.py us/Puerto-Rico	
python wahoo-map-creator-osmosis-route.py us/Rhode-Island	
python wahoo-map-creator-osmosis-route.py us/South-Carolina	
python wahoo-map-creator-osmosis-route.py us/South-Dakota	
python wahoo-map-creator-osmosis-route.py us/Tennessee	
python wahoo-map-creator-osmosis-route.py us/Texas
python wahoo-map-creator-osmosis-route.py us/us-virgin-islands	
python wahoo-map-creator-osmosis-route.py us/Utah	
python wahoo-map-creator-osmosis-route.py us/Vermont	
python wahoo-map-creator-osmosis-route.py us/Virginia	
python wahoo-map-creator-osmosis-route.py us/Washington	
python wahoo-map-creator-osmosis-route.py us/West-Virginia	
python wahoo-map-creator-osmosis-route.py us/Wisconsin	
python wahoo-map-creator-osmosis-route.py us/Wyoming	
python wahoo-map-creator-osmosis-route.py US
python wahoo-map-creator-osmosis-route.py north-america