python wahoo-map-creator-osmosis-route.py Algeria	
python wahoo-map-creator-osmosis-route.py Angola	
python wahoo-map-creator-osmosis-route.py Benin	
python wahoo-map-creator-osmosis-route.py Botswana	
python wahoo-map-creator-osmosis-route.py Burkina-Faso	
python wahoo-map-creator-osmosis-route.py Burundi	
python wahoo-map-creator-osmosis-route.py Cameroon	
python wahoo-map-creator-osmosis-route.py Canary-Islands	
python wahoo-map-creator-osmosis-route.py Cape-Verde	
python wahoo-map-creator-osmosis-route.py Central-African-Republic	
python wahoo-map-creator-osmosis-route.py Chad	
python wahoo-map-creator-osmosis-route.py Comores	
python wahoo-map-creator-osmosis-route.py Congo-Brazzaville	
python wahoo-map-creator-osmosis-route.py Congo-Democratic-Republic	
python wahoo-map-creator-osmosis-route.py Djibouti	
python wahoo-map-creator-osmosis-route.py Egypt	
python wahoo-map-creator-osmosis-route.py Equatorial-Guinea	
python wahoo-map-creator-osmosis-route.py Eritrea	
python wahoo-map-creator-osmosis-route.py Ethiopia	
python wahoo-map-creator-osmosis-route.py Gabon	
python wahoo-map-creator-osmosis-route.py Ghana	
python wahoo-map-creator-osmosis-route.py Guinea	
python wahoo-map-creator-osmosis-route.py Guinea-Bissau	
python wahoo-map-creator-osmosis-route.py Ivory-Coast	
python wahoo-map-creator-osmosis-route.py Kenya	
python wahoo-map-creator-osmosis-route.py Lesotho	
python wahoo-map-creator-osmosis-route.py Liberia	
python wahoo-map-creator-osmosis-route.py Libya	
python wahoo-map-creator-osmosis-route.py Madagascar	
python wahoo-map-creator-osmosis-route.py Malawi	
python wahoo-map-creator-osmosis-route.py Mali	
python wahoo-map-creator-osmosis-route.py Mauritania	
python wahoo-map-creator-osmosis-route.py Mauritius	
python wahoo-map-creator-osmosis-route.py Morocco	
python wahoo-map-creator-osmosis-route.py Mozambique	
python wahoo-map-creator-osmosis-route.py Namibia	
python wahoo-map-creator-osmosis-route.py Niger	
python wahoo-map-creator-osmosis-route.py Nigeria	
python wahoo-map-creator-osmosis-route.py Rwanda	
python wahoo-map-creator-osmosis-route.py Saint-Helena-Ascension-and-Tristan-da-Cunha	
python wahoo-map-creator-osmosis-route.py Sao-Tome-and-Principe	
python wahoo-map-creator-osmosis-route.py Senegal-and-Gambia	
python wahoo-map-creator-osmosis-route.py Seychelles	
python wahoo-map-creator-osmosis-route.py Sierra-Leone	
python wahoo-map-creator-osmosis-route.py Somalia	
python wahoo-map-creator-osmosis-route.py South-Africa	
python wahoo-map-creator-osmosis-route.py South-Sudan	
python wahoo-map-creator-osmosis-route.py Sudan	
python wahoo-map-creator-osmosis-route.py Swaziland	
python wahoo-map-creator-osmosis-route.py Tanzania	
python wahoo-map-creator-osmosis-route.py Togo	
python wahoo-map-creator-osmosis-route.py Tunisia	
python wahoo-map-creator-osmosis-route.py Uganda	
python wahoo-map-creator-osmosis-route.py Zambia	
python wahoo-map-creator-osmosis-route.py Zimbabwe	
python wahoo-map-creator-osmosis-route.py Africa
