python wmc-e.py algeria
python wmc-e.py angola
python wmc-e.py benin
python wmc-e.py botswana
python wmc-e.py burkina-faso
python wmc-e.py burundi
python wmc-e.py cameroon
python wmc-e.py canary-islands
python wmc-e.py cape-verde
python wmc-e.py central-african-republic
python wmc-e.py chad
python wmc-e.py comores
python wmc-e.py congo-brazzaville
python wmc-e.py congo-democratic-republic
python wmc-e.py djibouti
python wmc-e.py egypt
python wmc-e.py equatorial-guinea
python wmc-e.py eritrea
python wmc-e.py ethiopia
python wmc-e.py gabon
python wmc-e.py ghana
python wmc-e.py guinea
python wmc-e.py guinea-bissau
python wmc-e.py ivory-coast
python wmc-e.py kenya
python wmc-e.py lesotho
python wmc-e.py liberia
python wmc-e.py libya
python wmc-e.py madagascar
python wmc-e.py malawi
python wmc-e.py mali
python wmc-e.py mauritania
python wmc-e.py mauritius
python wmc-e.py morocco
python wmc-e.py mozambique
python wmc-e.py namibia
python wmc-e.py niger
python wmc-e.py nigeria
python wmc-e.py rwanda
python wmc-e.py saint-helena-ascension-and-tristan-da-cunha
python wmc-e.py sao-tome-and-principe
python wmc-e.py senegal-and-gambia
python wmc-e.py seychelles
python wmc-e.py sierra-leone
python wmc-e.py somalia
python wmc-e.py south-africa
python wmc-e.py south-sudan
python wmc-e.py sudan
python wmc-e.py swaziland
python wmc-e.py tanzania
python wmc-e.py togo
python wmc-e.py tunisia
python wmc-e.py uganda
python wmc-e.py zambia
python wmc-e.py zimbabwe
