python wahoo-map-creator-osmosis-route.py anhui
python wahoo-map-creator-osmosis-route.py beijing
python wahoo-map-creator-osmosis-route.py chongqing
python wahoo-map-creator-osmosis-route.py fujian
python wahoo-map-creator-osmosis-route.py gansu
python wahoo-map-creator-osmosis-route.py guangdong
python wahoo-map-creator-osmosis-route.py guangxi
python wahoo-map-creator-osmosis-route.py guizhou
python wahoo-map-creator-osmosis-route.py hainan
python wahoo-map-creator-osmosis-route.py hebei
python wahoo-map-creator-osmosis-route.py heilongjiang
python wahoo-map-creator-osmosis-route.py henan
python wahoo-map-creator-osmosis-route.py hong-kong
python wahoo-map-creator-osmosis-route.py hubei
python wahoo-map-creator-osmosis-route.py hunan
python wahoo-map-creator-osmosis-route.py inner-mongolia
python wahoo-map-creator-osmosis-route.py jiangsu
python wahoo-map-creator-osmosis-route.py jiangxi
python wahoo-map-creator-osmosis-route.py jilin
python wahoo-map-creator-osmosis-route.py liaoning
python wahoo-map-creator-osmosis-route.py macau
python wahoo-map-creator-osmosis-route.py ningxia
python wahoo-map-creator-osmosis-route.py qinghai
python wahoo-map-creator-osmosis-route.py shaanxi
python wahoo-map-creator-osmosis-route.py shandong
python wahoo-map-creator-osmosis-route.py shanghai
python wahoo-map-creator-osmosis-route.py shanxi
python wahoo-map-creator-osmosis-route.py sichuan
python wahoo-map-creator-osmosis-route.py tianjin
python wahoo-map-creator-osmosis-route.py tibet
python wahoo-map-creator-osmosis-route.py xinjiang
python wahoo-map-creator-osmosis-route.py yunnan
python wahoo-map-creator-osmosis-route.py zhejiang
