python wahoo-map-creator-osmosis-route.py argentina
python wahoo-map-creator-osmosis-route.py bolivia
python wahoo-map-creator-osmosis-route.py brazil
python wahoo-map-creator-osmosis-route.py centro-oeste
python wahoo-map-creator-osmosis-route.py chile
python wahoo-map-creator-osmosis-route.py colombia
python wahoo-map-creator-osmosis-route.py ecuador
python wahoo-map-creator-osmosis-route.py guyana
python wahoo-map-creator-osmosis-route.py nordeste
python wahoo-map-creator-osmosis-route.py norte
python wahoo-map-creator-osmosis-route.py paraguay
python wahoo-map-creator-osmosis-route.py peru
python wahoo-map-creator-osmosis-route.py sudeste
python wahoo-map-creator-osmosis-route.py sul
python wahoo-map-creator-osmosis-route.py suriname
python wahoo-map-creator-osmosis-route.py uruguay
python wahoo-map-creator-osmosis-route.py venezuela
