python wmc-e.py american-oceania
python wmc-e.py australia
python wmc-e.py cook-islands
python wmc-e.py fiji
python wmc-e.py ile-de-clipperton
python wmc-e.py kiribati
python wmc-e.py marshall-islands
python wmc-e.py micronesia
python wmc-e.py nauru
python wmc-e.py new-caledonia
python wmc-e.py new-zealand
python wmc-e.py niue
python wmc-e.py palau
python wmc-e.py papua-new-guinea
python wmc-e.py pitcairn-islands
python wmc-e.py polynesie-francaise
python wmc-e.py samoa
python wmc-e.py solomon-islands
python wmc-e.py tokelau
python wmc-e.py tonga
python wmc-e.py tuvalu
python wmc-e.py vanuatu
python wmc-e.py wallis-et-futuna
